# Generated by Django 4.0 on 2022-02-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='team_meamber')),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=300)),
                ('linkedin', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
    ]
