# Generated by Django 4.0 on 2022-02-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_teacher_image_alter_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='twitter',
        ),
    ]
