# Generated by Django 4.0 on 2022-03-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_teacher_facebook_remove_teacher_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=1, upload_to='teacher'),
            preserve_default=False,
        ),
    ]
