# Generated by Django 4.0 on 2022-01-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('fee', models.FloatField()),
                ('mode', models.BooleanField(default=False)),
                ('decsription', models.TextField()),
            ],
        ),
    ]
