# Generated by Django 4.0 on 2022-01-03 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_activity_rename_mode_course_paid_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.topic'),
            preserve_default=False,
        ),
    ]
