# Generated by Django 4.0 on 2022-01-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_activity_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default=1, upload_to='course_images/'),
            preserve_default=False,
        ),
    ]
