# Generated by Django 4.0 on 2022-01-05 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
