# Generated by Django 3.2.3 on 2021-06-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Url', models.CharField(max_length=300)),
                ('Description', models.TextField()),
                ('Course_class', models.IntegerField()),
                ('Subject', models.CharField(max_length=100)),
                ('Chapter', models.CharField(max_length=100)),
                ('Topic', models.CharField(max_length=100)),
            ],
        ),
    ]
