# Generated by Django 3.2.3 on 2021-06-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
